かな検索用画面のUIだけ実装
suzuka-kosen-festa/2022-monaqa pull request #13
Opened 2022-10-20 02:50 UTC by Sansai-snct

API叩くところとかはまだですあくまでUIだけ。
動けばヨシの精神なのでスタイリングも雑です。
issueの立て方的にPRの粒度大きくなってしまったことをお詫び申し上げます。
Remove UI sense

2022-10-20 13:14 UTC, re-taro requested changes

2022-10-20 13:14 UTC, re-taro commented on src/components/common/Form.tsx
> +const Form: FC<FormInterface> = ({ children, buttonText }) => (
これformバリデーションかけてください。入力されているかいないかだけでいいので。あとはsqlインジェクション対策だけ

2022-10-20 13:15 UTC, re-taro requested changes
testはsnap shotだけなのがちょっと...
Formのインプットテストとバリデーションテストぐらいはしてもいいと思います

2022-10-20 14:39 UTC, Sansai-snct commented on src/components/common/Form.tsx
> +const Form: FC<FormInterface> = ({ children, buttonText }) => (
[64d9a05](https://github.com/suzuka-kosen-festa/2022-monaqa/pull/13/commits/64d9a05499baa03f7f03bd69a910e5e8c274b51e)

2022-10-20 16:03 UTC, Sansai-lsz commented
バリデーションの有用性わからん
値なしで検索かけても空帰ってくるだけだしそこまで重要じゃない気が

2022-10-20 17:12 UTC, re-taro commented
値無しは良いとして今回はSQLインジェクションだけは避けなくてはいけない

2022-10-20 17:18 UTC, re-taro commented
testが走っていないな。huskyで

2022-10-20 17:19 UTC, re-taro commented
それだけ保証できるように変えてもらえません？

2022-10-20 23:23 UTC, Sansai-snct commented
> それだけ保証できるように変えてもらえません？

ok

2022-10-21 01:33 UTC, Sansai-snct commented
test走るようになったけど 
```
PASS  Waiting for file changes...
       press h to show help, press q to quit 
```
こっから動かん

2022-10-21 01:50 UTC, Sansai-snct commented
> それだけ保証できるように変えてもらえません？

[723f9f4](https://github.com/suzuka-kosen-festa/2022-monaqa/pull/13/commits/723f9f4ddc3abed373931d53242cc08547ffa074)

2022-10-21 04:49 UTC, re-taro approved these changes

2022-10-21 04:50 UTC, merged