認証周りの実装
suzuka-kosen-festa/2022-monaqa pull request #17
Opened 2022-10-24 23:53 UTC by Sansai-snct

jwt突破
ルーティングなど
リダイレクト処理はまだです。
これmergeされたら講習会用の仮リリースする。

2022-10-25 02:32 UTC, re-taro requested changes

2022-10-25 02:32 UTC, re-taro commented on src/components/utils/axios.ts
> +  baseURL: 'https://server-gytmf4azxa-uw.a.run.app/',
これ秘匿化してください。commitは削除してください

2022-10-25 04:01 UTC, Sansai-snct commented on src/components/utils/axios.ts
> +  baseURL: 'https://server-gytmf4azxa-uw.a.run.app/',
https://github.com/suzuka-kosen-festa/2022-monaqa/pull/17/commits/454a2f76345b48c09336c62fc5b61a6e822fecdd

2022-10-26 01:38 UTC, re-taro approved these changes

2022-10-26 01:42 UTC, merged