環境構築した
suzuka-kosen-festa/2022-monaqa pull request #3
Opened 2022-09-30 14:34 UTC by Sansai-snct

# やったこと
- 環境構築した
- husky使ってます
# 見てほしいところ
- 全体的に見ておかしいところ
- lintのルール
- config周り

2022-09-30 18:18 UTC, re-taro requested changes
名前を変更

https://github.com/suzuka-kosen-festa/2022-monaqa/blob/79488f427bfd9c9a2318d8c8d0c8f992ca84ee03/package.json#L2

2022-09-30 18:22 UTC, re-taro requested changes
推奨はこの形

```ts
const container = document.querySelector("#root") as HTMLElement;
const root = createRoot(container);
```

https://github.com/suzuka-kosen-festa/2022-monaqa/blob/79488f427bfd9c9a2318d8c8d0c8f992ca84ee03/src/main.tsx#L6-L7

2022-09-30 18:25 UTC, re-taro requested changes
testはない感じですか？あとhuskyが回ってるので大丈夫だとは思いますが、CIがあると良いかもです。huskyを絶対に外さないのならCIはいりませんが

2022-10-01 02:29 UTC, Sansai-snct commented
> testはない感じですか？あとhuskyが回ってるので大丈夫だとは思いますが、CIがあると良いかもです。huskyを絶対に外さないのならCIはいりませんが
testはvitestを導入しようかと思ったけど、テストの書き方わかんなくて沼りそうだったので入れませんでした。書けって言われたら頑張って書きます。CIはcommitするときにhusky回してるしいいかなあと思って回してなかった。

2022-10-02 06:35 UTC, re-taro commented
CIについては了解です、huskyを外してcommitしていないものとして認識しておくので外さないようにしてください。testについては、なくても良いですが事故が起こった場合はなんとかしてください。UIレビューの観点からStorybookほしいなぁとは思いますが、おまかせします。導入しない場合は実装したもののスクショなどが都度PRに貼ってあるとありがたいです。

2022-10-02 07:25 UTC, Sansai-snct commented
> CIについては了解です、huskyを外してcommitしていないものとして認識しておくので外さないようにしてください。testについては、なくても良いですが事故が起こった場合はなんとかしてください。UIレビューの観点からStorybookほしいなぁとは思いますが、おまかせします。導入しない場合は実装したもののスクショなどが都度PRに貼ってあるとありがたいです。

CIについてはこのままhuskyで行きます。testとstorybookは導入する方向で進めていくけど、どっちも自分で環境構築したことないからセットアップに時間かかるかも。

2022-10-02 07:29 UTC, re-taro commented
厳しければ導入しましょうか？

2022-10-02 07:31 UTC, Sansai-snct commented
まじ〜？
めちゃめちゃ助かるけどタスク的に大丈夫？

2022-10-02 07:32 UTC, re-taro commented
やれるわよ。コピペなので、とりあえずこれapproveしときます

2022-10-02 07:33 UTC, re-taro approved these changes

2022-10-02 23:58 UTC, merged